services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    networks:
      - kafka-net  # Подключаем сеть
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"  # Оставляем только в одном проекте!

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    networks:
      - kafka-net  # Подключаем сеть
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"  # Оставляем только в одном проекте!
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092  # Исправлено
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

networks:
  kafka-net:
    external: true